### ISSUE TITLE
loaded() always returns 1.

### ISSUE THREAD

**Issue by bolli24** [gnembon/scarpet#10]
Even used on blocks in chunks that were never generated before the loaded() function returns 1.

**Comment by gnembon** [comment]
Yeah, noticed that as well - OmegaLOL - by accident in reformatting I made all calls to loaded and loaded_ep - load that block. Its already fixed in current running master on carpetmod. Will release in some time as a public release, but for now you would need to wait, or build yourself form the carpetmod repo.

**Comment by gnembon** [comment]
fixed on carpetmod master

**Comment by bolli24** [comment]
Great to hear that. Thanks!
