### ISSUE TITLE
Add ability to trigger spawning attempt

### ISSUE THREAD

**Issue by aria1th** [gnembon/scarpet#111]
spawn_attempt(pos, category) or spawn_attempt(x, y, z, category)
-> generates spawning attempt once at a given position. if the position is not eligible, mobs does not spawn as it should be. else, mob spawning attempt generates regarding its structure and biome, and mobcaps. 

Why do we need this -
Example script

```
__config()->m(l('stay_loaded',true), l('scope','global'));

__on_tick_nether()-> (
	for(entity_list('living'), if((_~'type'=='zombie'||_~'type'=='chicken'&&_~'is_ridden')&&light(_~'pos')>7&&(_~'age'<2),
		modify(_, 'remove')	);
		if(   block(_~'pos')=='wither_rose' && (_~'type'!='wither_skeleton')&&(_~'category'=='monster')&&(_~'age'<2),				,
		modify(_, 'remove')	)
	);
null
);
```

then we will kill illegal zombie spawn instantly, and introduces 1.16's wither rose spawning rule. But it's different from that it should be, because it generates spawning attempt first, and removes the mob. It makes mobcap slightly less filled.

**Comment by aria1th** [comment]
+ Maybe spawn() command should be tracked by log mobcaps too?

**Comment by gnembon** [comment]
well, that event would be checked unnecessarily many, many times a tick. This would help in your particular case , but will be a constant performance detriment for everybody.
That's why there are no block entity events, because you can have a lot of them in the world at once.

In normal circumstances I would expect couple hundred, or even thousand events of such type a tick. Its probably better to do the way you are doing.

plus scarpet events do NOT affect the outcome of the vanilla course of action. programmers are free to manipulate the environment around it that may change course of some events, but not directly.
