### ISSUE TITLE
'Signs for water streams' script not working properly.

### ISSUE THREAD

**Issue by Megaminx12** [gnembon/scarpet#130]
You get an annoying error message in chat even when it works.

**Comment by indoorjetpacks** [comment]
@Megaminx12 Do you mean you need to sneak when placing any sign on a block? Because "Sneak click while placing signs to place it without getting the 'Edit sign message' prompt" is the intended function - if you don't want to get the UI if you're placing lots of signs for water or lava flow blocking, you sneak click. 

@Ghoulboy78 was the inventory_set() function added because of other scarpet changes or a server issue? Using the app without that line still removes the sign from the player inventory in singleplayer. I don't have a carpet server setup to test on though.

**Comment by Megaminx12** [comment]
1) Yes, sorry for asking. Edited.
2) I will test. If it works without error message I will close the issue.

**Comment by Megaminx12** [comment]
Tested, the entire script doesn't work if I remove it.  Maybe I removed the incorrect thing? I'll leave this open for now.

**Comment by Megaminx12** [comment]
No fixes, closing issue.

**Comment by Megaminx12** [comment]
Update: Fixed, but there is a new issue.
