### ISSUE TITLE
Structure Blocks

### ISSUE THREAD

**Issue by Conando025** [gnembon/scarpet#20]
I'm trying to create a funktion that automatically adds an a to the name of the Block. One big issue is that I haven't found a way to reed out the name of the current Structure Block. Another Problem is the fact that if you run `/script run set(x,y,z,'structure_block','mode','save')` the appearing Structure Block is still in data mode.

~I'm from Germany therefor my english probably isn't the best

**Comment by Anderium** [comment]
This is ~probably~ a bug within minecraft itself, as using `/setblock x y z minecraft:structure_block[mode=save]` does not work either.
I think this is because everything important for structure blocks is saved in blockdata (the NBT I mean). So with commands the following would work:
`/setblock x y z minecraft:structure_block{name:"foo:bar",mode:"SAVE"}`
See [this](https://bugs.mojang.com/browse/MC-133312?jql=text%20~%20%22structure%20setblock%22) bug report

An option to solve this would be the following:
`/script run set(x,y,z, 'structure_block'); run('data merge block x y z {mode:"SAVE", name:"foo:bar"}')`
The run command has to be used as there is currently no way to modify the NBT directly (See in the documentation: CarpetExpression.html -> Entity API -> Entity Manipulation)

**Comment by Conando025** [comment]
thanks you really helped me. I've now managed to make a working function.Nonetheless I would like to ask weather or not there is a way to reed the NBT out. e.g I wan't to what the current name is. If I'm right `query(e,'nbt',path?)` wont work, because a structure Block isn't an entity.

**Comment by Anderium** [comment]
You are right, as far as my testing went you cannot create a workaround for this. The fact you can't access blockdata though, means that you can't let a program check for what a chest contains either.
This is indeed a gap in the language and it would be helpful to be able to also read out those things.
You can read out what's on a sign as well then. And check which beacon effects are set. It's all kinds of useful :)

**Comment by gnembon** [comment]
I agree that the block API is kind of lacking at this point - but I needed to start with something. Adding support for fetching and manipulating NBTs so there is no need to use run() for that is something I have planned for the future.

**Comment by Conando025** [comment]
are there any chances that this feature will be includet in V2?

**Comment by Megaminx12** [comment]
Please close this, it is annoying to see open issues that have been abandoned.
