### ISSUE TITLE
Copper oxidation only with air access

### ISSUE THREAD

**Issue by leon0399** [gnembon/scarpet#219]
**Is your feature request related to a problem? Please describe.**
Currently, Vanilla Minecraft only allows us to stop copper oxidation by waxing. But it will be useful, to add extra option, to check for adjacent air blocks, since oxidation in fact requires oxygen acces

**Describe the solution you'd like**
Before incrementing oxidation stage, check for adjacent blocks. If every block is solid - don't update stage

**Describe alternatives you've considered**
I'm open to any other alternatives

**Additional context**
I've been thinking of oxidized copper farm, but current vanilla setup will always require player interaction - for waxing blocks on required stage. But with this option it's possible to fully automate copper farm. Player is only needed to harvest copper blocks from some kind of "bank"

I'm ready to implement this feature by myself, it seems to be quiet easy, so I need your feedback, are you ready to merge this kind of feature

**Comment by altrisi** [comment]
This isn't possible with scarpet right now, since you can't hook into random ticks (you could technically make a big "hack" to store all copper positions everywhere in the loaded area and check every so often if it oxidized then change it back, but it would be ugly and quite expensive).

You would probably need to make a mod for this instead, should be quite simple: redirect copper's (or whatever abstract class makes it oxidizable) `hasRandomTicks()` function and return false if all adjacent blocks are solid.

**Comment by leon0399** [comment]
@gnembon is there any chance us getting ability to intercept into random ticks via carpet apps in a foreseeing future?

**Comment by Ghoulboy78** [comment]
Unlikely due to how random ticks work in relation to blocks, so Imma close this. If you want, open an issue in fabic-carpet repo, where it would be more appropriate.
