### ISSUE TITLE
Carpet stackableshulkerbox does not affect stack_size function

### ISSUE THREAD

**Issue by aria1th** [gnembon/scarpet#230]
**Describe the bug**
carpet mod's option stackableshulkerbox does not affect shulkerbox's stack size, so it always return 1.

**To Reproduce**
/script run stack_limit('shulker_box')
/carpet stackableShulkerBoxes true
/script run stack_limit('shulker_box')

**Expected behavior**
1 -> 64 

**Screenshots**
If applicable, add screenshots to help explain your problem. You should add the error stacktrace here if it is displayed.

**Environment**
 - Carpet version:any
 - Minecraft version:1.17.1

**Additional context**
its minor parity problem

**Comment by altrisi** [comment]
That function doesn't really change the actual stack size other than when stackinng on the ground (to prevent inventory desync when players don't have the mod installed). Therefore it makes sense that the stack size is 1.

If you want to fully change the stack size of empty shulker boxes you need to use Carpet Extra with the `shulkerBoxAlwaysStack` (or something similar, can't really remember), and it may (or may not, since it's conditional to specific nbt data) change the output of the function.

All in all regular shulker boxes still stack to 1, only empty ones don't!

**Comment by Ghoulboy78** [comment]
It's `emptyShulkerBoxStackAlways`, and it still only affects empty shulker boxes, as it's considered cheaty otherwise. Therefore, it is normal that `stack_limit('shulkerbox')` returns 1 always.
