### ISSUE TITLE
Creating New Blocks and Items with Scarpet

### ISSUE THREAD

**Issue by Zodsmar** [gnembon/scarpet#26]
Are their plans or is it even possible to add the ability to create new blocks and items in the game (even GUI's) I know Minecraft has added the ability to sort of make new items but it is still very limiting and one of the biggest limits with it, is creating custom crafting recipes for these items.

Would love to create new blocks and basically entire mods in the game just through scripts.

**Comment by gnembon** [comment]
I don't believe there is a way to create custom block models in Vanilla. Scarpet is not aiming to add any components that would make it incompatible with vanilla. Having said that, since recently I believe you can bring your own entity and item models with datapacks. If you need to add custom behaviours to these custom blocks, you should be able to do it with command system, or scarpet for sure.

**Comment by fxmorin** [comment]
gnembnon, you could mimic adding items by using a random item such as a stick with a specific tag would actually be a gun. Using the datapack logic to make it seem like it is a gun. It would have custom properties and all the fun stuff. Except it wouldn't be in the creative tab

**Comment by PegasusEpsilon** [comment]
I believe there are several mods that add that ability already (custom data values (NBT data or blockstates) on existing items resulting in custom models/textures being displayed as specified in resource packs). Optifine I think was the first to add it, I don't know if it still supports it.

Most people use (or used, idk if they still do) vanilla's golden shovel as a retextured item on servers that intend to deliver custom items, since nobody used the golden shovel, and then just disable its crafting recipe. That way you can use damage values on it, and that works well enough.

For blocks, you can add custom models (so long as they consist of a mess of (optionally rotated) cuboids), with textures attached however you want, in vanilla's resource packs, but you can't add custom blocks (or blockstates) to display those custom models *yet*, so you have to override a vanilla block instead. All we need is custom blocks and custom UIs able to be pushed from servers for somebody to implement industrialcraft in bukkit (or a similar modded server system, like scarpet), and support vanilla clients just fine.

For now, if you're looking to do something like industrialcraft, you can give the user a renamed stone block, place a sign on it when they put it on the floor that says "macerator", and when they right-click it, open a custom imaginary chest UI full of mostly glass panes that they can't pick up, except for the slots they're meant to use. You can't do this in scarpet, as far as i know, because it's missing the UI tomfoolery. Maybe UI stuff should be added to solve this ticket...

*Goes to mess with custom item models...*

**Comment by gnembon** [comment]
closing as making custom blocks and items is either outside of vanilla scope or part of resourcepacks, which could very well be synced up with the scarpet code or a vanilla datapack that runs it.
