### ISSUE TITLE
simply_harvest off-hand block deletetion 

### ISSUE THREAD

**Issue by TwoPointInfinity** [gnembon/scarpet#351]
**Describe the bug**
Off hand blocks are deleted while harvesting with simply_harvest

**To Reproduce**
1 place blocks in your off hand
2 harvest fully grown crops

**Expected behavior**
blocks in the off hand are not affected, moved to inventory or dropped if necessary. 

**Screenshots**
N/A

**Environment**
 - Carpet version: fabric-carpet-1.19.2-1.4.84+v221018
 - Minecraft version: 1.19.2

**Comment by rv3r** [comment]
This appears to affect the mainhand as well. The script harvests the crop, the player (who is right-clicking for any amount of time) sets the block on top of the farmland, and then the script sets the crop there instead of the block, which appears to "delete" the block from the inventory. Canceling the block placement still allows the block to get used. I'm working on a fix.
