### ISSUE TITLE
pos() should probably carry dimension information

### ISSUE THREAD

**Issue by PegasusEpsilon** [gnembon/scarpet#36]
```
particle('heart', pos(player))
```

... will generate particles at the targeted player's position in the dimension where the command is run, not in the dimension where the targeted player actually is.

Solve the bug how you like, but I think pos() carrying dimensional information (possibly as an optional 4th parameter for the sake of legacy code) is probably the best option.

**Comment by gnembon** [comment]
hmm, all the callbacks for player events should be running in the player dimension, also querying for players with '*' will only return players in the dimension of the calling. I personally don't see issues with running the scripts in the context of a particular level / world. What is the circumstance that makes it difficult to work with?

One practical thing that I could suggest is add an in_dimension('nether', expr) function that changes the dimension context for the expr, no matter how complex that expr is.

**Comment by PegasusEpsilon** [comment]
The issue is that I can't set down a repeating command block with ...

`script run particle('heart', pos(player('trolling_victim')))`

... in it, and have it actually bury him in particles all the time. He goes to the nether or the end, and the particles don't go with him, they stay in the overworld. Which is both not what I want, and very strange to see particles moving around the overworld with no apparent cause.

I could `execute as` to solve it, but you could also solve it by putting dimension information into pos(). Which results in less surprising behavior, if nothing else.

Having in_dimension(query(player, 'dimension'), particle(...)) would probably work, too, but putting dimension data into the 4th element of pos() tucks it neatly away where you generally don't have to think about it. It just works.

I guess do what you like, but I was very surprised to see the result of the particle command as specified above. Maybe I shouldn't have been.

**Comment by PegasusEpsilon** [comment]
Having slept on it, I'll present my case in a different way.

As a developer, I try to adhere to the principle of least surprise. Unless a user is using your software completely wrong, it should, whenever possible, do whatever is least surprising, regardless of what input it receives.

The location of a human, currently, can be assumed to be on Earth, but once humanity becomes an interplanetary species (we're bound to wind up on Mars, at least, at some point, if we don't blow ourselves up first), latitude, longitude, and altitude are no longer sufficient to locate a person. You must also include what planet they're on.

Asking scarpet to draw particles on a player with the obvious (but in this case, wrong) syntax `particle(type, pos(player))` *should* do exactly that. It is the least surprising thing to do, given that input. If you want to draw particles in their position in a different dimension, you *should*, in my opinion, be forced to do ...

`l(x, y, z, d) = pos(player);
particle(type, l(x, y, z, target_dimension));`

... since that code *looks* like it will do something pan-dimensional, it makes every kind of sense that it *should* do something pan-dimensional. but `particle(type, pos(player))` absolutely looks like it should draw particles on a player, regardless of where they are, and therefore, in my opinion, it absolutely *should* do exactly that.

That's my take on it, anyway. "WAI" is still a perfectly valid response, I just violently disagree with it, in terms of development philosophy.

**Comment by gnembon** [comment]
in command system, command unless used by `execute` execute in the dimension of the command block / command source / player etc. query for `player(name)` queries among all logged players, it may need to be applicable to only players in the current dimension.
That's the reason for many commandblock solutions you need to run three sets of commands for each dimension separately.
In case of executing a script with a commandblock in spawn chunks it will always refer to the overworld coordinates.
In scarpet, world context is carried with the execution the same way it is carried with other commands.  That's why event API doesn't have __on_tick() only, but __on_tick_ender() and __on_tick_nether() and the only thing that changes is the world context. Changing how pos() works would be really bad because it would ruin a simple triple-numbers call and would require all other API calls to accept extra dimension parameter.

Apart from that the `in_dimension()` call could very well accept not only string name of the dimension but also en entity, or a block type, as they carry the dimension with them as well. That would make using it much more clean and intuitive.
I agree about the dev philosophy, but there is also a minecraft command system reality in which scarpet API lives.

**Comment by gnembon** [comment]
ok, did something like that, should in in the next carpet release (1.0.8)
```
__on_tick() ->
(
	// on tick runs always in the overworld context like a commandblock located in spawn
	p = player('gnembon');
	if (p,
		// since player can be in some other dimension
		in_dimension(p, 
			particle('end_rod',pos(p)+l(0,p~'eye_height',0)+(p~'look'),1,0)
		)
	)
)
```

**Comment by PegasusEpsilon** [comment]
I'd say anything that doesn't expect a 4th element from `pos()` would just ignore it, but then you have to think about if it should pass it through unmodified, or discard it. That would take some thinking.

As for `in_dimension()`, can you think of any other way to target a block in the nether, without a player in the nether to anchor to?

**Comment by gnembon** [comment]
in_dimension accepts entity, world localized block, or just a string: `in_dimension('nether',set(1,2,3,'stone'))`

**Comment by PegasusEpsilon** [comment]
Yes, but can you think of any *other* way to do it?
